# Basic
title: 潘柏信
subtitle: 个人站
description: 
creator: <a href="http://baixin.io">@leopardpan</a>

url: "http://baixin.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    

# 友情链接
flink:
    - {title: TakingDataSDK博客, description: TakingDataSDK博客, url: 'http://talkingdata.me'}     
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: leopard
    duoshuo: leopard 

# Social
social:
    weibo: 5366874726 
    github: leopardpan
    # twitter: 
    mail: leopardpan@icloud.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-84134159-3   
    host: auto  
